version: '3'

services:
  gin-mysql:
    image: mysql:5.7
    volumes:
      - "./init/mysql/init:/docker-entrypoint-initdb.d/"
    ports:
      - "63306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  gin-gorm-demo:
    scale: 3
    image: harbor.hd.com/gin-gorm-demo
    restart: always
    environment:
      - REDIS_ADDRESS=192.168.5.49:6379
      - WAIT_HOSTS=gin-mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - "gin-mysql"
    command: sh -c "/wait && /ginGormDemo"
    links:
      - "gin-mysql"

  gin-lb:
    image: dockercloud/haproxy:1.6.7
    links:
      - "gin-gorm-demo"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 88:80
    depends_on:
      - "gin-gorm-demo"
